default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: nasb-magento-quickbooks_development

test:
  <<: *default
  database: nasb-magento-quickbooks_test

staging:
  <<: *default
  database: nasb-magento-quickbooks_staging
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: nasb_magento_quickbooks_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host:     <%= ENV['DATABASE_HOST']%>
  port:     <%= ENV['DATABASE_PORT']%>
